# Generated by Django 5.2.7 on 2025-10-06 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                (
                    "codigo_cliente",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Código de Cliente"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("telefono", models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Cuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("concepto", models.CharField(max_length=255)),
                ("fecha_vencimiento", models.DateField()),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("pagada", models.BooleanField(default=False)),
                ("fecha_pago", models.DateField(blank=True, null=True)),
                (
                    "comprobante_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="frontend.cliente",
                        verbose_name="Cliente",
                    ),
                ),
            ],
            options={
                "ordering": ["fecha_vencimiento"],
            },
        ),
    ]
